name: aviation_weather
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  xml2json: ^5.3.5
  intl: ^0.17.0
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  firebase_analytics: ^10.0.0
  firebase_performance: ^0.9.0+2
  firebase_messaging: ^14.0.2
  google_mobile_ads:
    git: 
      url: https://github.com/jslattery26/googleads-mobile-flutter
      path: packages/google_mobile_ads
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  top_snackbar_flutter: ^2.1.1
  get_it: ^7.2.0
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.6
  google_maps_flutter: ^2.2.1
  google_maps_cluster_manager: ^3.0.0+1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  in_app_review: ^2.0.4
  flutter_toggle_tab: ^1.2.0
  enum_to_string: ^2.0.1
  pdf_render: ^1.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 800
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 500
