name: skylabs
description: SkyLabs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  internet_connection_checker: ^0.0.1+3
  connectivity: ^3.0.6
  flutter_svg: ^1.0.3
  get: ^4.3.8
  webview_flutter: ^3.0.4
  json_annotation: ^4.6.0
  grecaptcha: ^0.0.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.1
  auto_size_text: ^3.0.0
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  permission_handler: ^10.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/common/logo.png
  android: true
  ios: true

flutter_icons:
  image_path: 'assets/images/launcher-icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/common/logo.svg
    - assets/images/icons/hidden.svg
    - assets/images/icons/visible.svg
    - assets/images/icons/checkmark.svg
    - assets/images/widgets/onboarding/1.png
    - assets/images/widgets/onboarding/2.png
    - assets/images/widgets/onboarding/3.png
    - assets/images/widgets/onboarding/language.png
    - assets/files/config.json
    - assets/files/localizations/hy.json
    - assets/files/localizations/ru.json
    - assets/files/localizations/en.json

  fonts:
    - family: Mardoto
      fonts:
        - asset: assets/fonts/Mardoto/Mardoto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mardoto/Mardoto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mardoto/Mardoto-Bold.ttf
          weight: 700
